version: "3"
services:
  {{SERVICE_NAME}}:
    image: {{IMAGE_URL}}
    deploy:
      replicas: {{REPLICAS_NUMBER}}
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.5'
          memory: 4g

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/logBase/:/applog
      - /usr/share/fonts/zh:/usr/share/fonts/zh
      - /data/appBase/boc_mall/conf/context.xml:/usr/local/tomcat-8.5.27/conf/context.xml
      - /data/infrImgBase/tomcat/tomcat-8.5.27/lib:/usr/local/tomcat-8.5.27/lib
    environment:
      #Java runtime parameter with jmx exporter
      - "JAVA_OPTS=-server \
            -Xms{{XMS}} -Xmx{{XMX}} -XX:NewRatio=2 \
            -XX:NewSize={{NEWSIZE}} \
            -Dfile.encoding=UTF-8 \
            -Duser.language=zh_CN \
            -Dsun.jnu.encoding=UTF-8 \
            -Dcom.sun.management.jmxremote \
            -Djava.rmi.server.hostname=127.0.0.1 \
            -Dcom.sun.management.jmxremote.port=17000 \
            -Dcom.sun.management.jmxremote.ssl=false \
            -Dcom.sun.management.jmxremote.authenticate=false \
            -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled \
            -XX:+UseFastAccessorMethods \
            -XX:CMSInitiatingOccupancyFraction=70 \
            -Dapplog.prefix=$$HOSTNAME \
            -DAPPLOG={{APPLOG_PATH}} \
            -javaagent:/usr/local/JMXExporter/jmx_prometheus_javaagent-0.2.0-modified.jar=9404:/usr/local/JMXExporter/config.yml"
    ports:
      #应用端口
      - "{{APP_PORT}}:8080"
      #JMX Export端口
      #- "9404:9404"
#使用已有网络
networks:
  default:
      external:
        name: {{NETWORK_NAME}}
